### ISSUE TITLE
Some Fields Lost

### ISSUE THREAD

**Issue by JohnDoe-JohnDoe** [fgubler/PrivateContacts#29] opened 2023-10-06 15:27 UTC
Hi,
Thanks for a great app. Unfortunately I have an issue.
When I move a contact to "private", not all fields are moved. In particular the business name disappears and is lost for good. I haven't investigated all field so it might also happen to others.
Android 12 on Lenovo M8 tablet,

Thanks
JD

**Comment by fgubler** [comment] 2023-10-06 16:25
Hi,

First, I would like to thank you for the compliment. Second, I would like to apologize for the inconvenience.
I hope that no vital data was lost.

I have checked and you are 100% right. The company-name is currently not transferred. The reason for this is that the app uses a different way of storing company-information: it allows more than one company to be stored. As a result, transferring the company name was forgotten.

As this is a special case, I hope that this is indeed the only field to be lost. However, if you happen to have time for a more thorough investigation, I would of course be grateful for an update.

If you convert a single contact rather than bulk-mode, you can "check" to make sure that no data is lost, by simply opening the public contact in the app first and checking that everything is there. The same logic is used for loading a public contact to display it in the app as for making it private.

In the meantime, I have fixed the issue so in the next version, the company-name should be added as a "company" entry.

Best regards,
Florian

**Comment by JohnDoe-JohnDoe** [comment] 2023-10-06 16:33
Hi Florian,

Many thanks for your very fast reply.
Thankfully I was just testing the  app on a tablet to see if it is what I want, something I normally do before installing on my main phone. This means nothing important was lost. I will test the other fields over the weekend.
I look forward to the next version.

**Comment by fgubler** [comment] 2023-10-06 17:06
Glad to hear :-). That is a very smart habit, indeed 👍 .

**Comment by fgubler** [comment] 2023-10-09 17:21
Version 3.0.1 should now be available.

**Comment by JohnDoe-JohnDoe** [comment] 2023-10-11 23:53
Hi,

I have been trying the new version and it is still not quite right.
Company name shows as "Company Main" but when you move to secret and back again, it goes to:
"Related Person" with "Relationship" "Organisation:MAIN".  This means it doesn't show properly in the main contacts app or other apps allowed to access it.
Also, Related Person; "Assistant" moves to "Child". Other related person fields also change slightly, eg Father to Parent, I haven't tried all the others

The following field are also lost:
Work Title (I think you already know)
Department
All the phonetic names (not very important)
Name prefix (quite important)
Name suffix
Nick name
Labels

**Comment by fgubler** [comment] 2023-10-12 18:53
Thanks a lot for the feedback.
I will definitely have a close look at it and make some additions.

Infortunately, it will probably take me a few weeks. I am currently a bit under water in my day-job.

**Comment by fgubler** [comment] 2023-10-14 08:21
A bit of a more detailed response
- About the companies
  - Yes, there I have the problem that Private-Contacts supports multiple companies while the default Android contact-list only supports one (as far as I have been able to determine). Therefore this ugly workaround with storing them as Pseudo-relationships. I cannot solve that problem completely but would add logic which
     -  Stores the company in the company-field if there is only one company defined.
     - Stores the company with type "MAIN" in the company-field if there are multiple companies defined.
  - Does that make sense for you?
- About the relationships: Yes, the mapping is not quite 1:1 because when I looked around, different contact-apps offered different types and it was all a bit messy. Therefore, I decided to skip some distinctions (like only having "Parent" instead of "Mother" and "Father" and "Parent") when I thought the distinction does not matter so much (like I assume the user will know the gender with which that person identifies so "parent" contains the same amount of information as "father"). However, the "Assistand" becoming "Child" is definitely a bug. I will have to check whether it is on my side or in the library I use for accessing the contacts (in which case I will open a bug-ticket there)
- Work-Titel and Department: they don't quite fit the scheme of my database, but I will add them.
- Names (phonetic, prefix, postfix): I will add them. The nickname should already survive be there and be shown in the detail-screen. It is definitely not yet editable. But I will do some tests about whether it is lost when loaded from Android.
- Labels: I assume that with "label" you mean this ability to categorize contacts (like "family" or "work-colleagues" or "people I know from this sports-event"). If yes, this is of special interest to me because there is a bit of a short-coming in the contact-acccess-library which I use on that account. I thought, I had a work-around which should solve the issue but apparently, I missed something. 
  - I am aware that Private-Contacts does not yet have a UI to add or edit labels (that will come in the future). However, they should be shown in the detail-screen.
  - Do you happen to have multiple accounts on your device which contain contacts? (like multiple Google-Accounts for example,  or a private and a business-account)
  - The background is that those Labels are account-specific (i.e. the contact may correctly store the identifier of a label but if that label is stored in a different account than the contact, the "normal" contacts-app will not be able to match them).
  - This can easily be checked by moving a contact with a label from public to private, back to public: if the problem is the one mentioned above, the label would still be shown in the Private-Contacts app but not in the normal contacts app.

Generally speaking: I will probably add the features in the background first (i.e. new values will be copied over

**Comment by JohnDoe-JohnDoe** [comment] 2023-10-15 19:14
Thank you for your detailed reply.
I am only using the "on device" contacts as I don't share them with Google so no multiple accounts.
Most of the issues would be fine if there was a warning that those fields are not compatible and the data will be lost, you can then put extra information like that in the notes field.
I think it is important though to get the main fields working properly. With my test contact, this
![image](https://github.com/fgubler/PrivateContacts/assets/66528253/f2efa777-7af3-4230-9e0d-c048daba2faa)

becomes this
![image](https://github.com/fgubler/PrivateContacts/assets/66528253/b720d9d4-d565-47f6-afe8-c1668c917dfd)

when it has been moved to secret and back to public. As you can see, most of the info has gone (or moved).
Things like "father" becoming "parent" is fine if you are aware of it, some names are unisex so you wouldn't know if it is the mother or father, if you know that in advance you could put something like "Lesley (Mother)" & "Alex (Father)" in the fields.

The Label/Group thing is rather strange. This is called "Label" in the default contacts app, normally you would have "Work", "Personal", "Sports Club" etc. In the app it shows under "Groups" which is of course fine. The problem is every time you move the contact from Public to Private to Public this label is removed from the contact BUT another label is created with the same name but no entries, so I have ended up with this:
![image](https://github.com/fgubler/PrivateContacts/assets/66528253/faa9b714-a55a-4de1-a1b7-bc9f7d9f8fad)

3 Labels/Groups of the same name with no contacts in any of them. The contact doesn't show any Group/Label in either the default contacts app or Private Contacts.


I have also noticed that the "middle name" gets added to the end of the "first name", again, not a big problem as long as you you are aware this will happen.

Thanks,
JD

**Comment by fgubler** [comment] 2023-10-21 10:16
Thanks for the detailed feedback :-).
I will definitely have a look and get back to you when I have fixes.

**Comment by fgubler** [comment] 2024-02-20 10:46
Version 3.5.0 is now available

**Closed** 2024-03-06 17:45 UTC

**Comment by JohnDoe-JohnDoe** [comment] 2024-03-07 20:51
That's great, thanks for all your hard work fixing this.
________________________________
